### ISSUE TITLE
Window still registers input when not focused.

### ISSUE THREAD

**Issue by GoomiiV2** [themeldingwars/ImTool#1]
The imgui items like buttons will sill receive and respond to input if the window is covered by another one, this can cause unintended inputs to be clicked.

We could try blocking button inputs when the window doesn't have focus to prevent this but still have the cursor respond.

**Comment by ThiconZ** [comment]
This is most likely occurring due to the SDL_GetGlobalMouseState call for interacting with undocked and out of application ImTool windows.
https://github.com/themeldingwars/ImTool/blob/master/ImTool/ImGui/ImGuiController.cs#L713

https://wiki.libsdl.org/SDL_CaptureMouse
https://wiki.libsdl.org/SDL_GetGlobalMouseState

**Comment by freakbyte** [comment]
Fixed in 63435fe5fcd6194ddc46a0780dd4917f977bf819
